# Generated by Django 6.0 on 2026-01-12 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Promo', 'Badge'), ('Collection', 'Badge 0'), ('Nouveau', 'Badge 1'), ('Edition', 'Badge 2')], max_length=20, null=True)),
                ('className', models.CharField(blank=True, choices=[('light-pink', 'Pink'), ('light-blue', 'Blue'), ('light-green', 'Green'), ('light-orange', 'Orange')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('XXS', 'xxs'), ('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('XXL', 'xxl'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Taille',
                'verbose_name_plural': 'Tailles',
                'db_table': 'sizes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Etiquette',
                'verbose_name_plural': 'Etiquettes',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('ref', models.CharField(blank=True, max_length=10, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('newPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oldPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('warranty', models.IntegerField(blank=True, null=True)),
                ('imgDefault', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('imgHover', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('badge', models.ManyToManyField(to='api.badge')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('color', models.ManyToManyField(to='api.color')),
                ('size', models.ManyToManyField(to='api.size')),
                ('tag', models.ManyToManyField(to='api.tag')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
