# Generated by Django 6.0 on 2026-01-12 23:53

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, to='api.badge'),
        ),
    ]
