# Generated by Django 6.0 on 2026-05-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='value',
            new_name='color',
        ),
    ]
